set -g default-terminal "screen-256color"

# auto renumber windows for no gaps
set -g renumber-windows on

# remap prefix
set -g prefix C-j
unbind C-b
bind C-j send-prefix

# shortcut to reload tmux config
unbind r
bind r source-file ~/.tmux.conf

# move window left and right
bind-key -n C-S-Left swap-window -t -1
bind-key -n C-S-Right swap-window -t +1
