set -g default-terminal "screen-256color"

# Set scrollback history to 10k
set -g history-limit 10000

# Set window and pane index to 1 (0 by default)
set -g base-index 1
setw -g pane-base-index 1

# Split windows with more logical keys (and add opening
# a new pane with the current directory)
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# Open new windows from the current dir also
bind c new-window -c "#{pane_current_path}"

# Auto renumber windows for no gaps
set -g renumber-windows on

# Use Vi keybindings in copy mode
setw -g mode-keys vi

# Map Vi movement keys as pane movement keys
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Use 'v' and 'y' to begin/copy selections as in Vim
bind -t vi-copy v begin-selection
bind -t vi-copy y copy-selection

# Resize panes using PREFIX H, J, K, L
bind H resize-pane -L 5
bind J resize-pane -D 5
bind K resize-pane -U 5
bind L resize-pane -R 5

# Mouse settings
set -g mode-mouse on
set -g mouse-resize-pane on
set -g mouse-select-pane on
set -g mouse-select-window on

# Resize a window based on the smallest client actually viewing
# it, not on the smallest one attached to the entire session
setw -g aggressive-resize on
